### ISSUE TITLE
Versioning Images

### ISSUE THREAD

**Issue by burtonr** [markhobson/docker-sqlpackage#2]
Would it be possible to mirror the version of the sqlpackage binary with the published Docker image?

In the current implementation, it could be `markhobson/sqlpackage:15.0.5084.2` or at least the first 2 numbers (`15.0`)

This would help a lot in ensuring that the users (me) don't have unexpected failures when a newer image is pushed with the `latest` tag.

It appears that you're using the Docker Hub integrated builds connected to this GitHub repository. I'd offer to help, but I obviously don't have access to your Docker Hub account! I could however help and write out the steps if you'd like.

**Comment by markhobson** [comment]
Hi @burtonr, I can see that would be helpful - sorry if the upgrade broke your builds!

What were you thinking, using Git tags to tag Docker images in Docker Hub? Something low maintenance would be good.

**Comment by burtonr** [comment]
Nothing broke, just trying to prevent future breaks.

I believe you can set the option to use the tag as the version in Docker Hub. It should be straight-forward, but it's been a while since I've set it up. Here's the [Docker Documentation](https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds) on that feature.

**Comment by markhobson** [comment]
I've created a `18.7` tag for the latest version. Not a big fan of Docker Hub creating distinct images for the same Git commit, but it'll do for now. Does that work for you?

**Comment by burtonr** [comment]
Hey @markhobson that looks great. Thank you!
